//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainStation23.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int PostID { get; set; }
        public string CommentBody { get; set; }
        public string UserType { get; set; }
        public int Likes { get; set; }
        public Nullable<int> Dislikes { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
